-- MySQL Script generated by MySQL Workbench
-- Thu Jul 22 21:57:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema universityDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `universityDB` ;

-- -----------------------------------------------------
-- Schema universityDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universityDB` DEFAULT CHARACTER SET utf8 ;
USE `universityDB` ;

-- -----------------------------------------------------
-- Table `universityDB`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`City` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`City` (
  `city_id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `is_there_courses` BINARY NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `city_id_UNIQUE` (`city_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Room` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Room` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `beds` TINYINT NOT NULL,
  PRIMARY KEY (`room_id`),
  UNIQUE INDEX `room_id_UNIQUE` (`room_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Faculty_Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Faculty_Member` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Faculty_Member` (
  `faculty_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NULL,
  `email` VARCHAR(62) NULL,
  `first_joined` TIMESTAMP NOT NULL,
  PRIMARY KEY (`faculty_id`),
  UNIQUE INDEX `faculty_id_UNIQUE` (`faculty_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Advisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Advisor` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Advisor` (
  `advisor_id` INT NOT NULL,
  `faculty` INT NOT NULL,
  PRIMARY KEY (`advisor_id`, `faculty`),
  CONSTRAINT `FK_ADVISOR_FACULTY_MEMBER`
    FOREIGN KEY (`faculty`)
    REFERENCES `universityDB`.`Faculty_Member` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Student` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(62) NOT NULL,
  `dob` TIMESTAMP NULL,
  `assigned_animal` TINYINT NULL DEFAULT 0,
  `advisor` INT NULL,
  `gpa` INT NULL,
  `city` INT NULL,
  `room` INT NULL,
  `monitor` INT NULL,
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `idStudent_UNIQUE` (`student_id` ASC) VISIBLE,
  INDEX `FK_student_city_idx` (`city` ASC) VISIBLE,
  INDEX `FK_student_room_idx` (`room` ASC) VISIBLE,
  INDEX `FK_STUDENT_ADVISOR_idx` (`advisor` ASC) VISIBLE,
  INDEX `FK_STUDENT_MONITOR_idx` (`monitor` ASC) VISIBLE,
  CONSTRAINT `FK_STUDENT_CITY`
    FOREIGN KEY (`city`)
    REFERENCES `universityDB`.`City` (`city_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_STUDENT_ROOM`
    FOREIGN KEY (`room`)
    REFERENCES `universityDB`.`Room` (`room_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_STUDENT_ADVISOR`
    FOREIGN KEY (`advisor`)
    REFERENCES `universityDB`.`Advisor` (`advisor_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_STUDENT_MONITOR`
    FOREIGN KEY (`monitor`)
    REFERENCES `universityDB`.`Faculty_Member` (`faculty_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Classroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Classroom` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Classroom` (
  `classroom_id` INT NOT NULL AUTO_INCREMENT,
  `max_occupancy` TINYINT NOT NULL,
  `is_lab` BINARY NOT NULL,
  PRIMARY KEY (`classroom_id`),
  UNIQUE INDEX `classroom_id_UNIQUE` (`classroom_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Time_Slot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Time_Slot` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Time_Slot` (
  `time_slot_id` INT NOT NULL AUTO_INCREMENT,
  `start_time` TIMESTAMP NOT NULL,
  `end_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`time_slot_id`),
  UNIQUE INDEX `time_slot_id_UNIQUE` (`time_slot_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Section` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Section` (
  `section_id` INT NOT NULL AUTO_INCREMENT,
  `total_sections` TINYINT NOT NULL,
  `next_available_section` TINYINT NOT NULL,
  PRIMARY KEY (`section_id`),
  UNIQUE INDEX `section_id_UNIQUE` (`section_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Course` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(7) NOT NULL,
  `section` INT NULL,
  `time_slot` INT NULL,
  `classroom` INT NULL,
  `city` INT NULL,
  `capacity` INT NULL,
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `course_id_UNIQUE` (`course_id` ASC) VISIBLE,
  INDEX `FK_COURSE_CITY_idx` (`city` ASC) VISIBLE,
  INDEX `FK_COURSE_CLASSROOM_idx` (`classroom` ASC) VISIBLE,
  INDEX `FK_COURSE_TIME_SLOT_idx` (`time_slot` ASC) VISIBLE,
  INDEX `FK_COURSE_SECTION_idx` (`section` ASC) VISIBLE,
  CONSTRAINT `FK_COURSE_CITY`
    FOREIGN KEY (`city`)
    REFERENCES `universityDB`.`City` (`city_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_COURSE_CLASSROOM`
    FOREIGN KEY (`classroom`)
    REFERENCES `universityDB`.`Classroom` (`classroom_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_COURSE_TIME_SLOT`
    FOREIGN KEY (`time_slot`)
    REFERENCES `universityDB`.`Time_Slot` (`time_slot_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_COURSE_SECTION`
    FOREIGN KEY (`section`)
    REFERENCES `universityDB`.`Section` (`section_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Department` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Department` (
  `department_id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(62) NULL,
  `phone_number` INT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Mailing_List`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Mailing_List` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Mailing_List` (
  `mail_id` INT NOT NULL AUTO_INCREMENT,
  `email_address` VARCHAR(62) NOT NULL,
  `content` VARCHAR(200) NULL,
  PRIMARY KEY (`mail_id`),
  UNIQUE INDEX `mail_id_UNIQUE` (`mail_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Sign_Up`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Sign_Up` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Sign_Up` (
  `student` INT NOT NULL,
  `mailing_list` INT NOT NULL,
  PRIMARY KEY (`student`, `mailing_list`),
  INDEX `FK_sign_up_mailing_list_idx` (`mailing_list` ASC) VISIBLE,
  CONSTRAINT `FK_SIGN_UP_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `universityDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SIGN_UP_MAILING_LIST`
    FOREIGN KEY (`mailing_list`)
    REFERENCES `universityDB`.`Mailing_List` (`mail_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Grader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Grader` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Grader` (
  `grader_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`grader_id`),
  UNIQUE INDEX `grader_id_UNIQUE` (`grader_id` ASC) VISIBLE,
  CONSTRAINT `FK_GRADER_STUDENT`
    FOREIGN KEY (`grader_id`)
    REFERENCES `universityDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Payment` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(15,2) NOT NULL,
  `student` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  UNIQUE INDEX `payment_id_UNIQUE` (`payment_id` ASC) VISIBLE,
  INDEX `FK_PAYMENT_STUDENT_idx` (`student` ASC) VISIBLE,
  CONSTRAINT `FK_PAYMENT_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `universityDB`.`Student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`School_Program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`School_Program` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`School_Program` (
  `program_id` INT NOT NULL AUTO_INCREMENT,
  `department` INT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`program_id`),
  UNIQUE INDEX `program_id_UNIQUE` (`program_id` ASC) VISIBLE,
  INDEX `FK_PROGRAM_DEPARTMENT_idx` (`department` ASC) VISIBLE,
  CONSTRAINT `FK_PROGRAM_DEPARTMENT`
    FOREIGN KEY (`department`)
    REFERENCES `universityDB`.`Department` (`department_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Exam` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Exam` (
  `exam_id` TINYINT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `next_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`exam_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Attend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Attend` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Attend` (
  `joined_id` INT NOT NULL AUTO_INCREMENT,
  `student` INT NOT NULL,
  `school_program` INT NOT NULL,
  PRIMARY KEY (`joined_id`),
  UNIQUE INDEX `joined_id_UNIQUE` (`joined_id` ASC) VISIBLE,
  INDEX `FK_JOIN_STUDENT_idx` (`student` ASC) VISIBLE,
  INDEX `FK_JOIN_PROGRAM_idx` (`school_program` ASC) VISIBLE,
  CONSTRAINT `FK_JOIN_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `universityDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_JOIN_PROGRAM`
    FOREIGN KEY (`school_program`)
    REFERENCES `universityDB`.`School_Program` (`program_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Enrollment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Enrollment` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Enrollment` (
  `enrollment_id` INT NOT NULL AUTO_INCREMENT,
  `student` INT NOT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`enrollment_id`),
  UNIQUE INDEX `enrollment_id_UNIQUE` (`enrollment_id` ASC) VISIBLE,
  INDEX `FK_ENROLLMENT_STUDENT_idx` (`student` ASC) VISIBLE,
  INDEX `FK_ENROLLMENT_COURSE_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `FK_ENROLLMENT_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `universityDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ENROLLMENT_COURSE`
    FOREIGN KEY (`course`)
    REFERENCES `universityDB`.`Course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Professor` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Professor` (
  `professor_id` INT NOT NULL AUTO_INCREMENT,
  `faculty` INT NOT NULL,
  `first_taught` TIMESTAMP NULL,
  `years_taught` TINYINT NULL,
  PRIMARY KEY (`professor_id`, `faculty`),
  INDEX `FK_PROFESSOR_FACULTY_idx` (`faculty` ASC) VISIBLE,
  CONSTRAINT `FK_PROFESSOR_FACULTY`
    FOREIGN KEY (`faculty`)
    REFERENCES `universityDB`.`Faculty_Member` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Lecturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Lecturer` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Lecturer` (
  `lecturer_id` INT NOT NULL AUTO_INCREMENT,
  `faculty` INT NOT NULL,
  `first_taught` TIMESTAMP NULL,
  `years_taught` TINYINT NULL,
  PRIMARY KEY (`lecturer_id`, `faculty`),
  UNIQUE INDEX `lecturer_id_UNIQUE` (`lecturer_id` ASC) VISIBLE,
  INDEX `FK_LECTURER_FACULTY_idx` (`faculty` ASC) VISIBLE,
  CONSTRAINT `FK_LECTURER_FACULTY`
    FOREIGN KEY (`faculty`)
    REFERENCES `universityDB`.`Faculty_Member` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Appoint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Appoint` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Appoint` (
  `appoint_id` INT NOT NULL AUTO_INCREMENT,
  `faculty` INT NOT NULL,
  `department` INT NOT NULL,
  PRIMARY KEY (`appoint_id`),
  UNIQUE INDEX `appoint_id_UNIQUE` (`appoint_id` ASC) VISIBLE,
  INDEX `FK_APPOINT_FACULTY_idx` (`faculty` ASC) VISIBLE,
  INDEX `FK_APPOINT_DEPARTMENT_idx` (`department` ASC) VISIBLE,
  CONSTRAINT `FK_APPOINT_FACULTY`
    FOREIGN KEY (`faculty`)
    REFERENCES `universityDB`.`Faculty_Member` (`faculty_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_APPOINT_DEPARTMENT`
    FOREIGN KEY (`department`)
    REFERENCES `universityDB`.`Department` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Enroll_Exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Enroll_Exam` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Enroll_Exam` (
  `enroll_exam_id` INT NOT NULL AUTO_INCREMENT,
  `student` INT NOT NULL,
  `exam` TINYINT NOT NULL,
  PRIMARY KEY (`enroll_exam_id`),
  UNIQUE INDEX `enroll_exam_id_UNIQUE` (`enroll_exam_id` ASC) VISIBLE,
  INDEX `FK_ENROLL_STUDENT_idx` (`student` ASC) VISIBLE,
  INDEX `FK_ENROLL_EXAM_idx` (`exam` ASC) VISIBLE,
  CONSTRAINT `FK_ENROLL_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `universityDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ENROLL_EXAM`
    FOREIGN KEY (`exam`)
    REFERENCES `universityDB`.`Exam` (`exam_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Building`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Building` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Building` (
  `building_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(95) NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`building_id`),
  UNIQUE INDEX `building_id_UNIQUE` (`building_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Dorm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Dorm` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Dorm` (
  `dorm_id` INT NOT NULL,
  `building` INT NOT NULL,
  PRIMARY KEY (`dorm_id`),
  INDEX `FK_DORM_BUILDING_idx` (`building` ASC) VISIBLE,
  CONSTRAINT `FK_DORM_BUILDING`
    FOREIGN KEY (`building`)
    REFERENCES `universityDB`.`Building` (`building_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Contain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Contain` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Contain` (
  `contain_id` INT NOT NULL AUTO_INCREMENT,
  `dorm` INT NOT NULL,
  `room` INT NULL,
  PRIMARY KEY (`contain_id`),
  UNIQUE INDEX `contain_id_UNIQUE` (`contain_id` ASC) VISIBLE,
  INDEX `FK_CONTAIN_DORM_idx` (`dorm` ASC) VISIBLE,
  INDEX `FK_CONTAIN_ROOM_idx` (`room` ASC) VISIBLE,
  CONSTRAINT `FK_CONTAIN_DORM`
    FOREIGN KEY (`dorm`)
    REFERENCES `universityDB`.`Dorm` (`dorm_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CONTAIN_ROOM`
    FOREIGN KEY (`room`)
    REFERENCES `universityDB`.`Room` (`room_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Credit_Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Credit_Card` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Credit_Card` (
  `credit_card_number` VARCHAR(24) NOT NULL,
  `payment` INT NOT NULL,
  PRIMARY KEY (`credit_card_number`),
  INDEX `FK_CREDIT_PAYMENT_idx` (`payment` ASC) VISIBLE,
  CONSTRAINT `FK_CREDIT_PAYMENT`
    FOREIGN KEY (`payment`)
    REFERENCES `universityDB`.`Payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Bank_Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Bank_Account` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Bank_Account` (
  `bank_account_number` VARCHAR(24) NOT NULL,
  `payment` INT NOT NULL,
  PRIMARY KEY (`bank_account_number`),
  INDEX `FK_BANK_PAYMENT_idx` (`payment` ASC) VISIBLE,
  CONSTRAINT `FK_BANK_PAYMENT`
    FOREIGN KEY (`payment`)
    REFERENCES `universityDB`.`Payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Waitlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Waitlist` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Waitlist` (
  `waitlist_id` INT NOT NULL AUTO_INCREMENT,
  `student` INT NOT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`waitlist_id`),
  UNIQUE INDEX `enrollment_id_UNIQUE` (`waitlist_id` ASC) VISIBLE,
  INDEX `FK_ENROLLMENT_STUDENT_idx` (`student` ASC) VISIBLE,
  INDEX `FK_ENROLLMENT_COURSE_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `FK_WAITLIST_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `universityDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_WAITLIST_COURSE`
    FOREIGN KEY (`course`)
    REFERENCES `universityDB`.`Course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Animal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Animal` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Animal` (
  `animal_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dob` TIMESTAMP NOT NULL,
  `animal_type` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`animal_id`),
  UNIQUE INDEX `animal_id_UNIQUE` (`animal_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Research`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Research` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Research` (
  `research_id` INT NOT NULL AUTO_INCREMENT,
  `student` INT NOT NULL,
  `animal` INT NOT NULL,
  PRIMARY KEY (`research_id`),
  UNIQUE INDEX `research_id_UNIQUE` (`research_id` ASC) VISIBLE,
  INDEX `FK_RESEARCH_STUDENT_idx` (`student` ASC) VISIBLE,
  INDEX `FK_RESEARCH_ANIMAL_idx` (`animal` ASC) VISIBLE,
  CONSTRAINT `FK_RESEARCH_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `universityDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RESEARCH_ANIMAL`
    FOREIGN KEY (`animal`)
    REFERENCES `universityDB`.`Animal` (`animal_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Minor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Minor` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Minor` (
  `student` INT NOT NULL,
  `department` INT NOT NULL,
  PRIMARY KEY (`student`, `department`),
  CONSTRAINT `FK_MINOR_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `universityDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_MINOR_DEPARTMENT`
    FOREIGN KEY (`department`)
    REFERENCES `universityDB`.`Department` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Major` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Major` (
  `student` INT NOT NULL,
  `department` INT NOT NULL,
  PRIMARY KEY (`student`, `department`),
  CONSTRAINT `FK_MAJOR_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `universityDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_MAJOR_DEPARTMENT`
    FOREIGN KEY (`department`)
    REFERENCES `universityDB`.`Department` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Professor_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Professor_Course` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Professor_Course` (
  `professor` INT NOT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`professor`, `course`),
  INDEX `FK_PROFESSORCOURSE_PROFESSOR_idx` (`professor` ASC) VISIBLE,
  CONSTRAINT `FK_PROFESSORCOURSE_PROFESSOR`
    FOREIGN KEY (`professor`)
    REFERENCES `universityDB`.`Professor` (`professor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PROFESSORCOURSE_COURSE`
    FOREIGN KEY (`course`)
    REFERENCES `universityDB`.`Course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Lecturer_Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Lecturer_Course` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Lecturer_Course` (
  `lecturer` INT NOT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`lecturer`, `course`),
  INDEX `FK_LECTURERCOURSE_LECTURER_idx` (`lecturer` ASC) VISIBLE,
  CONSTRAINT `FK_LECTURERCOURSE_LECTURER`
    FOREIGN KEY (`lecturer`)
    REFERENCES `universityDB`.`Lecturer` (`lecturer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_LECTURERCOURSE_COURSE`
    FOREIGN KEY (`course`)
    REFERENCES `universityDB`.`Course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Author` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Author` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(25) NOT NULL,
  `last_name` VARCHAR(25) NOT NULL,
  `age` TINYINT NOT NULL,
  PRIMARY KEY (`author_id`),
  UNIQUE INDEX `author_id_UNIQUE` (`author_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Book` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Book` (
  `book_id` INT NOT NULL,
  `book_isbn` VARCHAR(20) NOT NULL,
  `title` VARCHAR(60) NOT NULL,
  `publisher` VARCHAR(25) NOT NULL,
  `publish_date` TIMESTAMP NOT NULL,
  `category` VARCHAR(25) NOT NULL,
  UNIQUE INDEX `book_isbn_UNIQUE` (`book_isbn` ASC) VISIBLE,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Writes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Writes` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Writes` (
  `writes_id` INT NOT NULL AUTO_INCREMENT,
  `author` INT NOT NULL,
  `book` INT NOT NULL,
  PRIMARY KEY (`writes_id`),
  UNIQUE INDEX `write_id_UNIQUE` (`writes_id` ASC) VISIBLE,
  INDEX `FK_WRITE_AUTHOR_idx` (`author` ASC) VISIBLE,
  INDEX `FK_WRITE_BOOK_idx` (`book` ASC) VISIBLE,
  CONSTRAINT `FK_WRITE_AUTHOR`
    FOREIGN KEY (`author`)
    REFERENCES `universityDB`.`Author` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_WRITE_BOOK`
    FOREIGN KEY (`book`)
    REFERENCES `universityDB`.`Book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Requires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Requires` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Requires` (
  `course` INT NOT NULL,
  `book` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`book`, `course`),
  INDEX `FK_REQUIRE_COURSE_idx` (`course` ASC) VISIBLE,
  INDEX `FK_REQUIRE_BOOK_idx` (`book` ASC) VISIBLE,
  CONSTRAINT `FK_REQUIRE_COURSE`
    FOREIGN KEY (`course`)
    REFERENCES `universityDB`.`Course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_REQUIRE_BOOK`
    FOREIGN KEY (`book`)
    REFERENCES `universityDB`.`Book` (`book_isbn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Resource_Link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Resource_Link` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Resource_Link` (
  `resource_link_id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(2048) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `category` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`resource_link_id`),
  UNIQUE INDEX `resource_links_id_UNIQUE` (`resource_link_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Links`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Links` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Links` (
  `resource_link` INT NOT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`resource_link`, `course`),
  INDEX `FK_LINKS_COURSE_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `FK_LINKS_RESOURCE_LINK`
    FOREIGN KEY (`resource_link`)
    REFERENCES `universityDB`.`Resource_Link` (`resource_link_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_LINKS_COURSE`
    FOREIGN KEY (`course`)
    REFERENCES `universityDB`.`Course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `universityDB`.`Grades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `universityDB`.`Grades` ;

CREATE TABLE IF NOT EXISTS `universityDB`.`Grades` (
  `grader` INT NOT NULL,
  `course` INT NOT NULL,
  `student` INT NOT NULL,
  PRIMARY KEY (`grader`, `course`, `student`),
  INDEX `FK_GRADERS_COURSE_idx` (`course` ASC) VISIBLE,
  INDEX `FK_GRADES_STUDENT_idx` (`student` ASC) VISIBLE,
  CONSTRAINT `FK_GRADES_GRADER`
    FOREIGN KEY (`grader`)
    REFERENCES `universityDB`.`Grader` (`grader_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_GRADES_COURSE`
    FOREIGN KEY (`course`)
    REFERENCES `universityDB`.`Course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_GRADES_STUDENT`
    FOREIGN KEY (`student`)
    REFERENCES `universityDB`.`Student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

DELIMITER //
CREATE TRIGGER UpdateStudentAfterResearchInsert AFTER INSERT ON Research
FOR EACH ROW
	BEGIN
		DECLARE researcher INT;
        SET researcher = new.student;
        UPDATE Student SET student.assigned_animal = 1 WHERE student_id = researcher;
    END //

DELIMITER //
CREATE TRIGGER UpdateCourseCapacity AFTER INSERT ON Enrollment
FOR EACH ROW
	BEGIN
		DECLARE course INT;
        SET course = new.course;
        UPDATE Course SET Course.capacity = Course.capacity + 1 WHERE Course = course;
    END //

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
